/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Main', {
    extend: 'Ext.Panel',

    config: {
        id: 'Main',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                id: 'MainTitle',
                scrollable: false,
                title: '로그인',
                items: [
                    {
                        xtype: 'button',
                        hidden: true,
                        id: 'KeyInputButton',
                        ui: 'action',
                        text: '강의등록',
                        align: 'right'
                    },
                    {
                        xtype: 'button',
                        hidden: true,
<<<<<<< HEAD
=======
                        id: 'QnAWriteButton',
                        ui: 'action',
                        text: '댓글쓰기',
                        align: 'right'
                    },
                    {
                        xtype: 'button',
                        hidden: true,
>>>>>>> b77cb8516038f0f7d87cb1a8f0b864a010a740c1
                        id: 'BackButton',
                        itemId: 'mybutton11',
                        ui: 'back',
                        text: 'Back'
                    }
                ]
            },
            {
                xtype: 'panel',
                id: 'LoginView',
                layout: {
                    type: 'card'
                },
                items: [
                    {
                        xtype: 'formpanel',
                        layout: {
                            align: 'center',
                            type: 'vbox'
                        },
                        items: [
                            {
                                xtype: 'fieldset',
                                title: 'Login',
                                items: [
                                    {
                                        xtype: 'emailfield',
<<<<<<< HEAD
                                        id: 'LoginEmailField',
                                        label: 'E-mail',
                                        name: 'Email',
=======
                                        label: 'E-mail',
>>>>>>> b77cb8516038f0f7d87cb1a8f0b864a010a740c1
                                        placeHolder: 'email@example.com'
                                    },
                                    {
                                        xtype: 'passwordfield',
<<<<<<< HEAD
                                        id: 'LoginPassField',
                                        label: 'Password',
                                        labelWidth: '36%',
                                        name: 'Password'
=======
                                        label: 'Password',
                                        labelWidth: '36%'
>>>>>>> b77cb8516038f0f7d87cb1a8f0b864a010a740c1
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                layout: {
                                    align: 'center',
                                    pack: 'center',
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'button',
                                        id: 'LoginButton',
                                        text: '로그인'
                                    },
                                    {
                                        xtype: 'spacer',
                                        width: 20
                                    },
                                    {
                                        xtype: 'button',
<<<<<<< HEAD
                                        id: 'SigninMoveButton',
=======
                                        id: 'SigninButton',
>>>>>>> b77cb8516038f0f7d87cb1a8f0b864a010a740c1
                                        text: '가입하기'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                id: 'LectureListView',
                layout: {
                    type: 'card'
                },
                items: [
                    {
                        xtype: 'list',
                        id: 'LectureList',
                        itemTpl: [
                            '<div>List Item {string}</div>'
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                id: 'KeyInputView',
<<<<<<< HEAD
                layout: {
                    align: 'center',
                    type: 'vbox'
                },
=======
>>>>>>> b77cb8516038f0f7d87cb1a8f0b864a010a740c1
                items: [
                    {
                        xtype: 'label',
                        height: 94,
                        html: '<br>여기에 고유번호 키를 입력해주세요 ',
                        padding: '1.3em',
                        ui: '',
                        width: 318
                    },
                    {
                        xtype: 'formpanel',
                        height: 203,
                        width: 318,
                        layout: {
                            type: 'vbox'
                        },
                        items: [
                            {
                                xtype: 'fieldset',
                                title: 'Key',
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        label: '키입력'
                                    }
                                ]
                            },
                            {
                                xtype: 'button',
                                id: 'RegisterButton',
                                text: '강의등록'
                            }
                        ]
                    }
                ]
            },
            {
<<<<<<< HEAD
                xtype: 'tabpanel',
                id: 'LectureTabPanel',
                hideOnMaskTap: false,
                layout: {
                    animation: 'cube',
                    type: 'card'
                },
                items: [
                    {
                        xtype: 'container',
                        id: 'IntroduceContainer',
                        layout: {
                            type: 'card'
                        },
                        title: '강의소개',
                        iconCls: 'info',
                        items: [
                            {
                                xtype: 'titlebar',
                                docked: 'top',
                                title: '강의소개',
                                items: [
                                    {
                                        xtype: 'button',
                                        id: 'TabBackButton1',
                                        ui: 'back',
                                        text: 'Back'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                id: 'IntroduceView',
                                layout: {
                                    align: 'center',
                                    type: 'vbox'
                                },
                                scrollable: false,
                                items: [
                                    {
                                        xtype: 'container',
                                        layout: {
                                            align: 'center',
                                            pack: 'center',
                                            type: 'hbox'
                                        },
                                        scrollable: false,
                                        items: [
                                            {
                                                xtype: 'image',
                                                height: 122,
                                                ui: '',
                                                width: 113
                                            },
                                            {
                                                xtype: 'label',
                                                html: '이름: 블라라<br>연락처: 010-4569-0000'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        height: 300,
                                        ui: '',
                                        width: 318,
                                        layout: {
                                            align: 'start',
                                            pack: 'center',
                                            type: 'hbox'
                                        },
                                        scrollable: true,
                                        items: [
                                            {
                                                xtype: 'label',
                                                html: '강의 소개 <br>어찌고 저찌고 abcdefghijklmnopqrstuvwxyz',
                                                margin: '1em'
                                            }
                                        ]
                                    }
                                ]
=======
                xtype: 'panel',
                id: 'MenuView',
                layout: {
                    align: 'center',
                    pack: 'center',
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'button',
                        id: 'IntroduceButton',
                        text: '강의소개'
                    },
                    {
                        xtype: 'spacer',
                        height: '2em'
                    },
                    {
                        xtype: 'button',
                        id: 'DataListButton',
                        text: '강의자료'
                    },
                    {
                        xtype: 'spacer',
                        height: '2em'
                    },
                    {
                        xtype: 'button',
                        id: 'QnAListButton',
                        text: '댓글목록'
                    }
                ]
            },
            {
                xtype: 'panel',
                id: 'IntroduceView',
                items: [
                    {
                        xtype: 'container',
                        layout: {
                            align: 'center',
                            pack: 'center',
                            type: 'hbox'
                        },
                        scrollable: false,
                        items: [
                            {
                                xtype: 'image',
                                height: 122,
                                ui: '',
                                width: 113
                            },
                            {
                                xtype: 'label',
                                html: '이름: 블라라<br>연락처: 010-4569-0000'
>>>>>>> b77cb8516038f0f7d87cb1a8f0b864a010a740c1
                            }
                        ]
                    },
                    {
                        xtype: 'container',
<<<<<<< HEAD
                        id: 'DataListContainer',
                        layout: {
                            type: 'card'
                        },
                        title: '자료목록',
                        activeItem: 1,
                        iconCls: 'download',
                        items: [
                            {
                                xtype: 'titlebar',
                                docked: 'top',
                                title: '자료목록',
                                items: [
                                    {
                                        xtype: 'button',
                                        id: 'TabBackButton2',
                                        ui: 'back',
                                        text: 'Back'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                id: 'DataListView',
                                ui: '',
                                layout: {
                                    type: 'card'
                                },
                                items: [
                                    {
                                        xtype: 'list',
                                        id: 'DataList'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        id: 'QnAListContainer',
                        layout: {
                            type: 'card'
                        },
                        title: '댓글목록',
                        activeItem: 2,
                        iconCls: 'compose',
                        items: [
                            {
                                xtype: 'titlebar',
                                docked: 'top',
                                title: '댓글목록',
                                items: [
                                    {
                                        xtype: 'button',
                                        id: 'QnAWriteButton',
                                        ui: 'action',
                                        text: '댓글쓰기',
                                        align: 'right'
                                    },
                                    {
                                        xtype: 'button',
                                        id: 'TabBackButton3',
                                        ui: 'back',
                                        text: 'Back'
                                    },
                                    {
                                        xtype: 'button',
                                        hidden: true,
                                        id: 'QnAWriteCanselButton',
                                        ui: 'action',
                                        text: '취소',
                                        align: 'right'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                id: 'QnAListView',
                                layout: {
                                    type: 'card'
                                },
                                items: [
                                    {
                                        xtype: 'list',
                                        id: 'QnAList',
                                        itemTpl: [
                                            '<div>질문 목록이 나오는 화면</div>'
                                        ]
                                    },
                                    {
                                        xtype: 'formpanel',
                                        id: 'QnAWriteView',
                                        layout: {
                                            align: 'center',
                                            pack: 'center',
                                            type: 'vbox'
                                        },
                                        scrollable: false,
                                        items: [
                                            {
                                                xtype: 'fieldset',
                                                instructions: '내용제한글자는 100자입니다',
                                                title: '댓글',
                                                items: [
                                                    {
                                                        xtype: 'textfield',
                                                        label: '이름'
                                                    },
                                                    {
                                                        xtype: 'textareafield',
                                                        height: 243,
                                                        width: 259,
                                                        label: '내용',
                                                        name: ''
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ],
                tabBar: {
                    docked: 'bottom',
                    id: 'LectureTabBar'
                }
=======
                        height: 300,
                        ui: '',
                        width: 318,
                        layout: {
                            align: 'start',
                            type: 'hbox'
                        },
                        scrollable: true,
                        items: [
                            {
                                xtype: 'label',
                                html: '강의 소개 <br>어찌고 저찌고 abcdefghijklmnopqrstuvwxyz',
                                margin: '1em'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                id: 'DataListView',
                layout: {
                    type: 'card'
                },
                items: [
                    {
                        xtype: 'list',
                        id: 'DataList',
                        itemTpl: [
                            '<div>List Item {string}</div>'
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                id: 'QnAListView',
                layout: {
                    type: 'card'
                },
                items: [
                    {
                        xtype: 'list',
                        id: 'QnAList',
                        itemTpl: [
                            '<div>List Item {string}</div>'
                        ]
                    }
                ]
            },
            {
                xtype: 'formpanel',
                id: 'QnAWriteView',
                layout: {
                    align: 'center',
                    pack: 'center',
                    type: 'vbox'
                },
                scrollable: false,
                items: [
                    {
                        xtype: 'fieldset',
                        instructions: '내용제한글자는 100자입니다',
                        title: '댓글',
                        items: [
                            {
                                xtype: 'textfield',
                                label: '이름'
                            },
                            {
                                xtype: 'textareafield',
                                height: 260,
                                width: 261,
                                label: '내용',
                                name: ''
                            }
                        ]
                    }
                ]
>>>>>>> b77cb8516038f0f7d87cb1a8f0b864a010a740c1
            },
            {
                xtype: 'formpanel',
                id: 'SigninView',
                layout: {
                    align: 'center',
                    type: 'vbox'
                },
                scrollable: false,
                items: [
                    {
                        xtype: 'fieldset',
                        title: '이메일 인증',
                        items: [
                            {
                                xtype: 'emailfield',
<<<<<<< HEAD
                                id: 'SigninEmailField',
=======
>>>>>>> b77cb8516038f0f7d87cb1a8f0b864a010a740c1
                                width: 278,
                                label: 'Email',
                                placeHolder: 'email@example.com'
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        id: 'MailSendButton',
                        text: '인증메일발송'
                    },
                    {
                        xtype: 'spacer',
                        height: '1em'
                    },
                    {
                        xtype: 'fieldset',
                        instructions: '비밀번호는 여기서 사용할 비밀번호입니다.',
                        title: '정보입력',
                        items: [
                            {
                                xtype: 'textfield',
<<<<<<< HEAD
                                id: 'SigninNumField',
=======
>>>>>>> b77cb8516038f0f7d87cb1a8f0b864a010a740c1
                                label: '인증번호'
                            },
                            {
                                xtype: 'passwordfield',
<<<<<<< HEAD
                                id: 'SigninPassField',
=======
>>>>>>> b77cb8516038f0f7d87cb1a8f0b864a010a740c1
                                label: '비밀번호'
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        id: 'SigninButton',
                        text: '가입하기'
                    }
                ]
            }
        ]
    }

});